name: pr-labeler

on: [pull_request]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: gustavopergola/pr-labeler@f5b2825b69bd449a6f54db7ae43dd81c297311f6
        with:
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          exclude_files: '.txt'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}